### ISSUE TITLE
How to access fastify request logger in service implementation?

### ISSUE THREAD

**Issue by StarpTech** [bufbuild/connect-es#698] opened 2023-06-30 10:09 UTC
**Is your feature request related to a problem? Please describe.**
How to access fastify request logger in service implementation?

**Describe the solution you'd like**
A way to enrich the handler context ourselves or access the fastify request instance within the connect `ctx`

Please specify whether the request is for Connect for Web or Connect for
Node.js.

**Describe alternatives you've considered**
If you've proposed a solution, are there any alternatives? Why are they worse
than your preferred approach?

**Additional context**

**Comment by smaye81** [comment] 2023-07-07 21:01
Closing as a duplicate of https://github.com/bufbuild/connect-es/issues/708.

**Closed by smaye81** 2023-07-07 21:01 UTC
Labels: enhancement
